import XCTest
@testable import ThreadMac

/// The local-history readers are pure: records in, conversation out. Fixtures mirror each tool's
/// real on-disk records (trimmed).
final class LocalHistoryTests: XCTestCase {
    private func lines(_ jsonl: String) -> [[String: Any]] {
        jsonl.split(separator: "\n").compactMap {
            (try? JSONSerialization.jsonObject(with: Data($0.utf8))) as? [String: Any]
        }
    }

    func testClaudeCodeKeepsPromptsAndProseDropsToolsMetaAndSidechains() {
        let records = lines(#"""
        {"type":"summary","summary":"Pricing model","leafUuid":"a2"}
        {"type":"user","isMeta":true,"sessionId":"s1","uuid":"m0","timestamp":"2026-10-01T10:00:00.000Z","message":{"role":"user","content":"Caveat: The messages below were generated by the user while running local commands."}}
        {"type":"user","sessionId":"s1","uuid":"u1","timestamp":"2026-10-01T10:00:01.000Z","message":{"role":"user","content":"Should we charge per seat?"}}
        {"type":"assistant","sessionId":"s1","uuid":"a1","timestamp":"2026-10-01T10:00:02.000Z","message":{"id":"msg_1","role":"assistant","content":[{"type":"thinking","thinking":"hidden"},{"type":"text","text":"Per seat scales with value."}]}}
        {"type":"assistant","sessionId":"s1","uuid":"a1b","timestamp":"2026-10-01T10:00:03.000Z","message":{"id":"msg_1","role":"assistant","content":[{"type":"tool_use","id":"t1","name":"Read","input":{}}]}}
        {"type":"user","sessionId":"s1","uuid":"tr1","timestamp":"2026-10-01T10:00:04.000Z","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1","content":"file contents"}]}}
        {"type":"assistant","sessionId":"s1","uuid":"a2","timestamp":"2026-10-01T10:00:05.000Z","message":{"id":"msg_1","role":"assistant","content":[{"type":"text","text":"But it discourages adding people."}]}}
        {"type":"user","sessionId":"s1","isSidechain":true,"uuid":"sc1","timestamp":"2026-10-01T10:00:06.000Z","message":{"role":"user","content":"subagent prompt"}}
        {"type":"user","sessionId":"s1","uuid":"c1","timestamp":"2026-10-01T10:00:07.000Z","message":{"role":"user","content":"<command-name>/clear</command-name>"}}
        {"type":"user","sessionId":"s1","uuid":"u2","timestamp":"2026-10-01T10:01:00.000Z","message":{"role":"user","content":[{"type":"text","text":"Then bill per active member."}]}}
        {not json — a line being written
        """#)
        let c = ClaudeCodeHistory.parse(records, fallbackId: "file")!
        XCTAssertEqual(c.id, "s1")
        XCTAssertEqual(c.messages.map(\.role), ["user", "assistant", "user"])
        XCTAssertEqual(c.messages[0].text, "Should we charge per seat?")
        XCTAssertEqual(c.messages[1].text, "Per seat scales with value.\n\nBut it discourages adding people.")
        XCTAssertEqual(c.messages[2].text, "Then bill per active member.")
        XCTAssertEqual(c.messages[2].createdAt, "2026-10-01T10:01:00.000Z")
    }

    func testClaudeCodeSessionWithoutAPromptIsNotAConversation() {
        let records = lines(#"""
        {"type":"summary","summary":"x","leafUuid":"y"}
        """#)
        XCTAssertNil(ClaudeCodeHistory.parse(records, fallbackId: "f"))
    }

    func testFingerprintMovesWhenAReplyGrowsOrATurnIsAdded() {
        let m1 = LocalMessage(id: "1", role: "user", text: "hi", createdAt: "t")
        let a = LocalConversation(id: "c", messages: [m1, LocalMessage(id: "2", role: "assistant", text: "Hel", createdAt: "t")])
        let b = LocalConversation(id: "c", messages: [m1, LocalMessage(id: "2", role: "assistant", text: "Hello there", createdAt: "t")])
        let c = LocalConversation(id: "c", messages: b.messages + [LocalMessage(id: "3", role: "user", text: "ok", createdAt: "t")])
        XCTAssertNotEqual(LocalHistoryWatch.fingerprint(a), LocalHistoryWatch.fingerprint(b))
        XCTAssertNotEqual(LocalHistoryWatch.fingerprint(b), LocalHistoryWatch.fingerprint(c))
        XCTAssertEqual(LocalHistoryWatch.fingerprint(b), LocalHistoryWatch.fingerprint(b))
    }

    func testCodexUsesUserAndAgentEventsAndSkipsSubAgentThreads() {
        let c = CodexHistory.parse(lines(#"""
        {"timestamp":"2026-10-01T12:00:00.000Z","type":"session_meta","payload":{"id":"th1","cwd":"/app","thread_source":"user"}}
        {"timestamp":"2026-10-01T12:00:01.000Z","type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"<environment_context>...</environment_context>"}]}}
        {"timestamp":"2026-10-01T12:00:05.120Z","type":"event_msg","payload":{"type":"user_message","message":"add retries to fetch"}}
        {"timestamp":"2026-10-01T12:00:07.000Z","type":"event_msg","payload":{"type":"agent_reasoning","text":"hidden"}}
        {"timestamp":"2026-10-01T12:00:09.881Z","type":"event_msg","payload":{"type":"agent_message","message":"Done: exponential backoff, 3 tries."}}
        """#))!
        XCTAssertEqual(c.id, "th1")
        XCTAssertEqual(c.messages.map(\.role), ["user", "assistant"])
        XCTAssertEqual(c.messages[0].text, "add retries to fetch")
        XCTAssertNil(CodexHistory.parse(lines(#"""
        {"timestamp":"t","type":"session_meta","payload":{"id":"sub","parent_thread_id":"th1"}}
        {"timestamp":"t","type":"event_msg","payload":{"type":"user_message","message":"subtask"}}
        """#)))
    }

    func testGeminiCLIAppliesUpsertsSetAndRewind() {
        let c = GeminiCLIHistory.parse(lines(#"""
        {"sessionId":"g1","projectHash":"myapp","startTime":"2026-10-01T10:00:00Z","kind":"main"}
        {"id":"m1","timestamp":"2026-10-01T10:00:02Z","type":"user","content":[{"text":"explain @src/a.ts plus file body"}],"displayContent":"explain @src/a.ts"}
        {"id":"m2","timestamp":"2026-10-01T10:00:06Z","type":"gemini","content":"It par"}
        {"id":"m2","timestamp":"2026-10-01T10:00:07Z","type":"gemini","content":"It parses config."}
        {"id":"m3","timestamp":"2026-10-01T10:00:08Z","type":"info","content":"Tokens: 120"}
        {"id":"m4","timestamp":"2026-10-01T10:01:00Z","type":"user","content":"wrong question"}
        {"$rewindTo":"m4"}
        {"id":"m5","timestamp":"2026-10-01T10:02:00Z","type":"user","content":"why config first?"}
        """#))!
        XCTAssertEqual(c.id, "g1")
        XCTAssertEqual(c.messages.map(\.text), ["explain @src/a.ts", "It parses config.", "why config first?"])
        XCTAssertEqual(c.messages.map(\.role), ["user", "assistant", "user"])
    }

    func testCopilotReplaysTheMutationLog() {
        let session = CopilotChatHistory.replay(lines(#"""
        {"kind":0,"v":{"version":3,"sessionId":"cs1","creationDate":1759750000000,"requests":[]}}
        {"kind":2,"k":["requests"],"v":[{"requestId":"request_1","timestamp":1759750001000,"message":{"text":"why is this null?","parts":[]},"response":[]}]}
        {"kind":2,"k":["requests",0,"response"],"v":[{"kind":"toolInvocationSerialized","invocationMessage":"Reading file"},{"value":"Because `foo` is "}]}
        {"kind":2,"k":["requests",0,"response"],"v":[{"value":"never assigned."}]}
        {"kind":1,"k":["customTitle"],"v":"Null foo"}
        {"kind":2,"k":["requests"],"v":[{"requestId":"request_2","timestamp":1759750100000,"isSystemInitiated":true,"message":{"text":"auto"},"response":[]}]}
        """#))!
        let c = CopilotChatHistory.conversation(session)!
        XCTAssertEqual(c.id, "cs1")
        XCTAssertEqual(c.messages.map(\.text), ["why is this null?", "Because `foo` is never assigned."])
        XCTAssertEqual(session["customTitle"] as? String, "Null foo")
    }

    func testMutationLogPushTruncatesFirst() {
        let r = CopilotChatHistory.replay(lines(#"""
        {"kind":0,"v":{"sessionId":"x","requests":[{"requestId":"a"},{"requestId":"b"}]}}
        {"kind":2,"k":["requests"],"i":1,"v":[{"requestId":"c"}]}
        {"kind":3,"k":["requests",0]}
        """#))!
        XCTAssertEqual((r["requests"] as? [[String: Any]])?.compactMap { $0["requestId"] as? String }, ["c"])
    }

    func testJanReadsTextValuesAndMillisecondTimes() {
        let c = JanHistory.parse(lines(#"""
        {"id":"j1","object":"thread.message","thread_id":"t1","role":"user","content":[{"type":"text","text":{"value":"hi there","annotations":[]}}],"created_at":1759750000000}
        {"id":"j2","object":"thread.message","thread_id":"t1","role":"assistant","content":[{"type":"text","text":{"value":"Hello!","annotations":[]}}],"created_at":1759750002000}
        """#), threadId: "t1")!
        XCTAssertEqual(c.messages.map(\.text), ["hi there", "Hello!"])
        XCTAssertTrue(c.messages[0].createdAt.hasPrefix("2025-10-06"))
    }

    func testLMStudioTakesSelectedVersionAndSkipsThinking() throws {
        let obj = try JSONSerialization.jsonObject(with: Data(#"""
        {"name":"Pricing","messages":[
          {"versions":[{"role":"user","content":[{"type":"text","text":"per seat?"}]}]},
          {"currentlySelected":1,"versions":[
            {"role":"assistant","steps":[{"type":"contentBlock","content":[{"type":"text","text":"old answer"}]}]},
            {"role":"assistant","steps":[{"type":"contentBlock","style":{"type":"thinking"},"content":[{"type":"text","text":"hmm"}]},{"type":"contentBlock","content":[{"type":"text","text":"Yes, per seat."}]}]}
          ]}
        ]}
        """#.utf8)) as! [String: Any]
        let c = LMStudioHistory.parse(obj, id: "1759750000000", fallbackDate: "2026-10-01T00:00:00Z")!
        XCTAssertEqual(c.messages.map(\.text), ["per seat?", "Yes, per seat."])
    }
}
