import XCTest
@testable import ThreadMac

/// The local-history readers are pure: records in, conversation out. Fixtures mirror each tool's
/// real on-disk records (trimmed).
final class LocalHistoryTests: XCTestCase {
    private func lines(_ jsonl: String) -> [[String: Any]] {
        jsonl.split(separator: "\n").compactMap {
            (try? JSONSerialization.jsonObject(with: Data($0.utf8))) as? [String: Any]
        }
    }

    func testClaudeCodeKeepsPromptsAndProseDropsToolsMetaAndSidechains() {
        let records = lines(#"""
        {"type":"summary","summary":"Pricing model","leafUuid":"a2"}
        {"type":"user","isMeta":true,"sessionId":"s1","uuid":"m0","timestamp":"2026-10-01T10:00:00.000Z","message":{"role":"user","content":"Caveat: The messages below were generated by the user while running local commands."}}
        {"type":"user","sessionId":"s1","uuid":"u1","timestamp":"2026-10-01T10:00:01.000Z","message":{"role":"user","content":"Should we charge per seat?"}}
        {"type":"assistant","sessionId":"s1","uuid":"a1","timestamp":"2026-10-01T10:00:02.000Z","message":{"id":"msg_1","role":"assistant","content":[{"type":"thinking","thinking":"hidden"},{"type":"text","text":"Per seat scales with value."}]}}
        {"type":"assistant","sessionId":"s1","uuid":"a1b","timestamp":"2026-10-01T10:00:03.000Z","message":{"id":"msg_1","role":"assistant","content":[{"type":"tool_use","id":"t1","name":"Read","input":{}}]}}
        {"type":"user","sessionId":"s1","uuid":"tr1","timestamp":"2026-10-01T10:00:04.000Z","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1","content":"file contents"}]}}
        {"type":"assistant","sessionId":"s1","uuid":"a2","timestamp":"2026-10-01T10:00:05.000Z","message":{"id":"msg_1","role":"assistant","content":[{"type":"text","text":"But it discourages adding people."}]}}
        {"type":"user","sessionId":"s1","isSidechain":true,"uuid":"sc1","timestamp":"2026-10-01T10:00:06.000Z","message":{"role":"user","content":"subagent prompt"}}
        {"type":"user","sessionId":"s1","uuid":"c1","timestamp":"2026-10-01T10:00:07.000Z","message":{"role":"user","content":"<command-name>/clear</command-name>"}}
        {"type":"user","sessionId":"s1","uuid":"u2","timestamp":"2026-10-01T10:01:00.000Z","message":{"role":"user","content":[{"type":"text","text":"Then bill per active member."}]}}
        {not json — a line being written
        """#)
        let c = ClaudeCodeHistory.parse(records, fallbackId: "file")!
        XCTAssertEqual(c.id, "s1")
        XCTAssertEqual(c.messages.map(\.role), ["user", "assistant", "user"])
        XCTAssertEqual(c.messages[0].text, "Should we charge per seat?")
        XCTAssertEqual(c.messages[1].text, "Per seat scales with value.\n\nBut it discourages adding people.")
        XCTAssertEqual(c.messages[2].text, "Then bill per active member.")
        XCTAssertEqual(c.messages[2].createdAt, "2026-10-01T10:01:00.000Z")
    }

    func testClaudeCodeSessionWithoutAPromptIsNotAConversation() {
        let records = lines(#"""
        {"type":"summary","summary":"x","leafUuid":"y"}
        """#)
        XCTAssertNil(ClaudeCodeHistory.parse(records, fallbackId: "f"))
    }

    func testFingerprintMovesWhenAReplyGrowsOrATurnIsAdded() {
        let m1 = LocalMessage(id: "1", role: "user", text: "hi", createdAt: "t")
        let a = LocalConversation(id: "c", messages: [m1, LocalMessage(id: "2", role: "assistant", text: "Hel", createdAt: "t")])
        let b = LocalConversation(id: "c", messages: [m1, LocalMessage(id: "2", role: "assistant", text: "Hello there", createdAt: "t")])
        let c = LocalConversation(id: "c", messages: b.messages + [LocalMessage(id: "3", role: "user", text: "ok", createdAt: "t")])
        XCTAssertNotEqual(LocalHistoryWatch.fingerprint(a), LocalHistoryWatch.fingerprint(b))
        XCTAssertNotEqual(LocalHistoryWatch.fingerprint(b), LocalHistoryWatch.fingerprint(c))
        XCTAssertEqual(LocalHistoryWatch.fingerprint(b), LocalHistoryWatch.fingerprint(b))
    }
}
